export const CARD_SIZE = 5;

export const DATA = [
  {id: 1, description: "Eiffel Tower"},
  {id: 2, description: "Great Wall of China"},
  {id: 3, description: "Statue of Liberty"},
  {id: 4, description: "Taj Mahal"},
  {id: 5, description: "Machu Picchu"},
  {id: 6, description: "Pyramids of Giza"},
  {id: 7, description: "Colosseum"},
  {id: 8, description: "Christ the Redeemer"},
  {id: 9, description: "Petra, Jordan"},
  {id: 10, description: "Acropolis of Athens"},
  {id: 11, description: "Chichen Itza"},
  {id: 12, description: "Stonehenge"},
  {id: 13, description: "The Louvre"},
  {id: 14, description: "Sydney Opera House"},
  {id: 15, description: "Angkor Wat"},
  {id: 16, description: "Mount Rushmore"},
  {id: 17, description: "Neuschwanstein Castle"},
  {id: 18, description: "The Parthenon"},
  {id: 19, description: "The Kremlin"},
  {id: 20, description: "Mesa Verde"},
  {id: 21, description: "The Palace of Versailles"},
  {id: 22, description: "Mariana Trench"},
  {id: 23, description: "Mount Everest"},
  {id: 24, description: "Grand Canyon"},
  {id: 25, description: "Victoria Falls"},
  {id: 26, description: "Mars Rover"},
  {id: 27, description: "The Sphinx"},
  {id: 28, description: "Mona Lisa"},
  {id: 29, description: "The Vatican"},
  {id: 30, description: "Mesoamerican Pyramids"},
  {id: 31, description: "The Amazon Rainforest"},
];
